<?php

namespace SpecShaper\CalendarBundle\Repository;

/**
 * AgendaItemCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgendaItemCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
