<?php

namespace SpecShaper\CalendarBundle\Repository;

/**
 * AgendaItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgendaItemRepository extends \Doctrine\ORM\EntityRepository
{
}
