<?php

namespace SpecShaper\CalendarBundle\Repository;

/**
 * AgendaCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgendaCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
