<?php

namespace SpecShaper\CalendarBundle\Repository;

/**
 * CalendarEventRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarEventRepository extends \Doctrine\ORM\EntityRepository
{
}
