<?php

namespace SpecShaper\CalendarBundle\Repository;

/**
 * InviteeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InviteeRepository extends \Doctrine\ORM\EntityRepository
{
}
