<?php

namespace SpecShaper\CalendarBundle\Repository;

/**
 * MeetingCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeetingCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
