<?php

namespace SpecShaper\CalendarBundle\Repository;

/**
 * MeetingLocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MeetingLocationRepository extends \Doctrine\ORM\EntityRepository
{
}
