<?php

namespace SpecShaper\CalendarBundle\Repository;

/**
 * MinutesItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MinutesItemRepository extends \Doctrine\ORM\EntityRepository
{
}
