<?php

namespace SpecShaper\CalendarBundle\Repository;

/**
 * MinuteItemCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MinuteItemCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
