<?php

namespace SpecShaper\CalendarBundle\Repository;

/**
 * PersistedEventRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersistedEventRepository extends \Doctrine\ORM\EntityRepository
{
}
